### PR TITLE
Resinos 2

### PR DESCRIPTION
**Pull request by shaunmulligan**
This PR adds the following documentation on resinOS 2.0 versions:
* Networking setup
* migration from 1.X to 2.0
* description of what resinOS 2.0 consists of and what specific OS variants mean.

### CODE REVIEW

File: shared/insideResinOS/1.X.md [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+
+![Yocto Project Logo](/img/yocto.png)
+
+The operating system we install on your device is [Yocto][yocto] [Linux][linux]. This is an innovative distribution which comprises components which can be combined together to build a custom Linux system containing only the software you need for any target architecture. We plan to support additional Operating Systems bases in the future.
+
+This is perfect for Resin.io - we have built an optimised Linux system for the devices we support and can guarantee the same behaviour on any further devices we support in the future.
+
+## Application Environment
+
+On the device, we run the Resin Container Engine (RCE) which uses the power of [containerisation][containerisation] to provide a consistent environment for your software to operate inside at a far smaller performance penalty than virtualisation. Additionally since RCE runs Docker containers you have the freedom to provide custom [Dockerfiles][Dockerfile] giving you the ability to control exactly what is installed and run on the device.
```
Comment (imrehg) [inline shared/insideResinOS/1.X.md]: Do we still do RCE there on the 1.x line?

File: config/dictionaries/os_version.json [hunk 2]
```diff
@@ -0,0 +1,10 @@
+[
+  {
+    "id": "2.0",
```
Comment (craig-mulligan) [inline config/dictionaries/os_version.json]: Should this be Semvery? like 2.0.0? Or are we only documenting minor release changes?

File: pages/runtime/migrate-to-2.0.md [hunk 3]
```diff
@@ -0,0 +1,37 @@
+---
+title: Moving to resinOS 2.0
+excerpt: How to migrate code from 1.X to resinOS 2.0 and where the caveats are.
```
Comment (alisondavis17) [inline pages/runtime/migrate-to-2.0.md]: "How to migrate code from resinOS 1.x to 2.0 and what to watch out for"

File: pages/runtime/migrate-to-2.0.md [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+---
+## Migrating from 1.X to 2.0
+
+In resinOS a number of changes were introduced to improve reliability and connectivity. This guide will highlight some of the major changes and how those changes may affect your code.
```
Comment (alisondavis17) [inline pages/runtime/migrate-to-2.0.md]: "In resinOS 2.0"

File: pages/runtime/migrate-to-2.0.md [hunk 5]
```diff
@@ -0,0 +1,37 @@
...
+
+Perhaps one of the largest changes in 2.0 is the change in the connection manager. ResinOS now uses [NetworkManager][networkmanager-link] and [ModemManager][modemmanager-link] to provide a robust and flexible networking stack. This change has enabled much more simple and effective [GSM/cellular connectivity](/deployment/network/2.0/#cellular-modem-setup) and overall [simpler network configuration](/deployment/network/2.0/#introduction) process. However, this change has meant we had to remove the old connection manager [connman][connman-link] and deprecate its interfaces.
```
Comment (alisondavis17) [inline pages/runtime/migrate-to-2.0.md]: connman should be ConnMan throughout

File: shared/networking/1.X.md [hunk 6]
```diff
@@ -0,0 +1,159 @@
...
+
+If you require this functionality in your devices, you should have a look at our captive portal project called [Resin Wifi Connect][wifi-connect-link] and its associated [blog post][wifi-connect-blog]
+
+### Troubleshooting
+
+If you have issues connecting with the WiFi device, first check to ensure the
+SSID and passphrase are correct. If they are, try rebooting with an ethernet
+cable plugged in, then booting again with just WiFi.
+
+If neither of these approaches work, drop us a line at support@resin.io!
```
Comment (imrehg) [inline shared/networking/1.X.md]: Link to the forums instead of the support email? Or what's our current policy regarding support emails?

File: pages/runtime/migrate-to-2.0.md [hunk 7]
```diff
@@ -0,0 +1,37 @@
...
+
+Another significant change is in the way the container [update locking mechanism][update-locks-link] behaves. In resinOS 2.0 update lock now needs to be created in `/tmp/resin/`. The reason for this change is to fix an issue in the locking mechanism over device power cycle where the resin.io supervisor would not be able to determine if the lock was originally taken by itself or a user container before the power was pulled. So in this case the supervisor would remove the lock and erroneously update the container that should have been locked.
+
+To prevent this case from happening, the lock is now written to a `tmpfs` which means its automatically cleared when the power is cut. What this means for your code is that it will need to always take the lock as soon as it's container is started up. In this way it can ensure it will never be updated until the lock is [overridden from the dashboard](https://docs.resin.io/management/devices/#update-locking) or your code.
```
Comment (alisondavis17) [inline pages/runtime/migrate-to-2.0.md]: it's should be its

File: pages/runtime/migrate-to-2.0.md [hunk 8]
```diff
@@ -0,0 +1,37 @@
...
+
+Other smaller, but important changes to note are the following:
+- `/host_run/dbus` is now deprecate in favour of `/host/run/dbus`, this newer path was actually introduced in devices that are running resin supervisor `1.7.0` or greater, so in most case you should be able to just update the path and your code will work for both 1.X and 2.0 devices.
```
Comment (alisondavis17) [inline pages/runtime/migrate-to-2.0.md]: deprecated

File: shared/networking/1.X.md [hunk 9]
```diff
@@ -0,0 +1,159 @@
...
+* `*.resin.io`
+* `*.pubnub.com`
+
+Additionally make an outgoing connection to `mixpanel.com`, but this is not a functional requirement for resin.io, but rather allows us to track some useful metrics.
+
+## Ethernet Connections
+
+As mentioned earlier, resin.io HostOS defaults to using ethernet for internet connectivity, so if you connect an active ethernet cable to your device and all the [network requirements](#network-requirements) are satisfied, your device should simply just connect to dashboard.resin.io and you should be able to push code to it.
+
+If this this is not the case, and your device is still not online 10 minutes after power up, then give us a shout at `support@resin.io` or click on the small **`?`** in the bottom right of your resin.io dashboard.
```
Comment (imrehg) [inline shared/networking/1.X.md]: Support changes?

File: shared/networking/2.0.md [hunk 10]
```diff
@@ -0,0 +1,202 @@
+# Networking on resinOS 2.0
```
Comment (craig-mulligan) [inline shared/networking/2.0.md]: As far as I understand doxx partials this will only be selected when selecting `resinos 2.0` this looks like more general info that should be pulled in for 2.x filter. If this is the case it's something we should look at later.

File: shared/insideResinOS/1.X.md [hunk 11]
```diff
@@ -0,0 +1,38 @@
+# What's On The Device?
+
+The [Resin.io][resin] software running on your device leverages a number of powerful components to provide great functionality at a minimal performance cost:-
```
Comment (alisondavis17) [inline shared/insideResinOS/1.X.md]: Resin.io should be resin.io (lowercase) throughout

File: shared/insideResinOS/1.X.md (hunk 1 above)
Comment (alisondavis17) [inline shared/insideResinOS/1.X.md]: is there supposed to be a link for containerisation?

Comment (alisondavis17) [inline shared/insideResinOS/1.X.md]: "run on the device" should be "runs on the device"

File: shared/insideResinOS/1.X.md [hunk 12]
```diff
@@ -0,0 +1,38 @@
...
+
+![Resin.io Logo](/img/logo_supervisor.svg)
+
+The Resin.io supervisor is a lightweight process which runs on your device, manages your applications and communicates with our servers - downloading new applications and updates to existing applications as you push them, sending logs to your dashboard, as well as updating itself automatically when new releases of the supervisor are pushed out by us.
+
+## Your Application
+
+![Application Image](/img/logo_app.svg)
+
+Once your device has booted and the initial setup is complete, the Supervisor contacts our servers and downloads the latest version of your application.
```
Comment (alisondavis17) [inline shared/insideResinOS/1.X.md]: supervisor should either consistently be lowercase or uppercase

File: shared/insideResinOS/2.0.md [hunk 13]
```diff
@@ -0,0 +1,154 @@
...
+
+ResinOS is an operating system built for easy portability to multiple device types (via the [Yocto framework](https://www.yoctoproject.org/)) and optimised for Linux Containers, and Docker in particular. There are many decisions, large and small, we have made to enable that vision, which are present throughout our architecture.
+
+The first version of ResinOS was developed as part of resin.io, and has run on thousands of embedded devices, deployed in many different contexts for several years. ResinOS v2 represents the combination of the learnings we extracted over those years, as well as our determination to make ResinOS a first-class open source project, able to run as an independent operating system, for any context where embedded devices and containers intersect.
```
Comment (alisondavis17) [inline shared/insideResinOS/2.0.md]: ResinOS should be lowercase resinOS throughout (except at the start of a sentence)

File: shared/networking/2.0.md [hunk 14]
```diff
@@ -0,0 +1,202 @@
...
+
+* [Introduction](#introduction)
+* [Wifi Setup](#wifi-setup)
+* [Setting a Static IP](#setting-a-static-ip)
+* [Cellular Modem Setup](#cellular-modem-setup)
+* [Network Requirements](#network-requirements)
+
+## Introduction
+
+In resinOS 2.0 the connectivity management has been change from [connman][connman-link] to [NetworkManager][networkmanager-link]. NetworkManager give the OS a bit more flexibility in the network setup and in conjunction with [ModemManager][modemmanager-link] allows resinOS to offer first class [GSM/Cellular support](#setup-a-cellular-connection).
```
Comment (craig-mulligan) [inline shared/networking/2.0.md]: NetworkManager give the OS a bit more flexibility in the network setup -> NetworkManager allows resinOS more flexibility when configuring the network. 

(or just drop the `a bit`)

File: shared/insideResinOS/2.0.md (hunk 13 above)
Comment (alisondavis17) [inline shared/insideResinOS/2.0.md]: developed "as part of the resin.io platform" and has run on "thousands of embedded devices on resin.io"

File: shared/insideResinOS/2.0.md [hunk 15]
```diff
@@ -0,0 +1,154 @@
...
+
+## Variants of ResinOS
+
+ResinOS currently comes in 3 different variants all built from the same source but with slightly differing features enabled or disabled. Each version of resinOS produces the following variants:
+
+| Version Name | Variant Type | Description |
+|:------------:|:------------:|:------------:|
+| 2.0.0.rev1   | production   | This is the production version of the resin.io managed OS. This is the OS you should use for any production fleet deployments |
+| 2.0.0.rev1-dev | development | This version the development version of the above and should be used when you are developing a new application and want to use the fast [local mode][local-mode-link] workflow |
+| 2.0.0.rev1-standalone | standalone | This version is an unmanaged version of resinOS, it doesn't not have the resin.io supervisor and does not connect to the management console. Use this variant if you want a stable linux OS to run docker on. |
```
Comment (alisondavis17) [inline shared/insideResinOS/2.0.md]: remove double negative so just reads "doesn't have the resin.io supervisor"

File: shared/insideResinOS/2.0.md [hunk 16]
```diff
@@ -0,0 +1,154 @@
...
+We look forward to working with the community to grow and mature ResinOS into an operating system with even broader device support, a broader operating envelope, and as always, taking advantage of the most modern developments in security and reliability.
+
+## Variants of ResinOS
+
+ResinOS currently comes in 3 different variants all built from the same source but with slightly differing features enabled or disabled. Each version of resinOS produces the following variants:
+
+| Version Name | Variant Type | Description |
+|:------------:|:------------:|:------------:|
+| 2.0.0.rev1   | production   | This is the production version of the resin.io managed OS. This is the OS you should use for any production fleet deployments |
+| 2.0.0.rev1-dev | development | This version the development version of the above and should be used when you are developing a new application and want to use the fast [local mode][local-mode-link] workflow |
```
Comment (alisondavis17) [inline shared/insideResinOS/2.0.md]: let's add another warning here not to use dev versions in production

Comment (alisondavis17) [inline shared/insideResinOS/2.0.md]: need to add local mode link

File: shared/networking/2.0.md [hunk 17]
```diff
@@ -0,0 +1,202 @@
...
+
+All of the network configuration for resinOS can be done though files in the boot partition of your device. I you have a freshly downloaded resinOS `.img` you can mount it and inspect the `resin-boot` or `resin-flash` (for devices that boot from eMMC) partition. In the boot partition you will find a directory called `system-connections`.
+
+The `system-connections` directory consists of a set of "connection files" one file per connection. If you added a wifi connection at from the Dashboard when you downloaded your image, you should see two connection files `resin-wifi` and `resin-sample`. Both of these files are define a `wifi` connection type, but `resin-sample` is just a template or example file which you can copy to create new connections. You will notice that there is no file for ethernet, this is because NetworkManager will always set up a default ethernet connection. Most of the allowed options for these connection files can be found in the [NetworkManager settings reference][nm-setting-ref]
```
Comment (craig-mulligan) [inline shared/networking/2.0.md]: Dashboard -> unnecessary capitalisation.

File: shared/networking/2.0.md [hunk 18]
```diff
@@ -0,0 +1,202 @@
...
+addr-gen-mode=stable-privacy
+method=auto
+
+[wifi-security]
+auth-alg=open
+key-mgmt=wpa-psk
+psk=super_secret_wifi_password
+```
+
+This file sets up a simple wifi connection to a network named `My Awesome Wifi Ssid` with a wifi password (`psk`) of `super_secret_wifi_password`. If you want to add multiple different wifi credentials, then simply make a copy of `resin-wifi` or `resin-sample` and change the `SSID` and `psk` key values. You can also add the `autoconnect-priority` key in each file to define the priority of each connection when the device has multiple wifi connections it can connect to.
```
Comment (craig-mulligan) [inline shared/networking/2.0.md]: What value do you need to set with `autoconnect-priority`?

File: shared/insideResinOS/2.0.md (hunk 15 above)
Comment (alisondavis17) [inline shared/insideResinOS/2.0.md]: Docker should be capitalized throughout

Comment (alisondavis17) [inline shared/insideResinOS/2.0.md]: make sure variant names are updated to reflect name change

File: shared/insideResinOS/2.0.md [hunk 19]
```diff
@@ -0,0 +1,154 @@
...
+
+### Dev vs. Prod images
+
+The Development images are recommended while getting started with resinOS and building a system.
+The dev images enable a number of useful features while developing, namely:
+
+* Passwordless SSH into resinOS on port `22222` as the root user. So one can do `ssh root@<DEVICE_IP> -p22222` and poke around to see how the system runs.
+* Docker socket exposed on via port `2377`, which allows `resin local push` to do remote docker builds on the target device.
+* Getty console attached to tty1 and serial.
+* Capable of entering [local mode][local-mode-link] for rapid development of application containers locally.
```
Comment (alisondavis17) [inline shared/insideResinOS/2.0.md]: add local mode link

File: shared/insideResinOS/2.0.md [hunk 20]
```diff
@@ -0,0 +1,154 @@
...
+buffer in order to avoid wear on the flash storage used by most of the supported boards. However, persistent logging can be enabled by setting
+the `"persistentLogging": true` key in the `config.json` file in the boot partition of the device.
+
+Both Prod and Dev variants will also allow the setting of a custom hostname via the `config.json`, just add `"hostname": "my-new-hostname"`. Your device will then broadcast (via Avahi) on the network as `my-new-hostname.local`. If you don't set a custom hostname, the device will default to `<short-UUID>.local`.
+
+On the production variant, nothing is written to tty1, on boot up you should only see the resin logo on the HDMI screen and this will persist until your application code takes over the framebuffer. If you would like to replace the resin logo with your own custom splash logo, then you will need to replace splash/resin-logo.png file that you will find in the first partition of our images (boot partition or `resin-boot`) with your own image. NOTE: As it currently stands plymouth expects the image to be named `resin-logo.png`.
```
Comment (alisondavis17) [inline shared/insideResinOS/2.0.md]: Should be consistent in capitalizing (or not) Development, Production, Standalone, Unmanaged

File: shared/networking/2.0.md [hunk 21]
```diff
@@ -0,0 +1,202 @@
...
+* ONDA MT191UP (USB AT command)
+* Huawei E8231s-2 (USB Ethernet emulation)
+* Huawei E3531i-2 (USB Ethernet emulation)
+* Huawei E3131 (USB Ethernet emulation)
+* [Fona 3G](https://learn.adafruit.com/adafruit-fona-3g-cellular-gps-breakout/overview) (USB AT command)
+* uBlox lisa-u200 (USB AT command)
+* Huawei ME909u-521
+* Huawei E398-u1 (cdc-wdm0) --> This device took a while to connect, most likely because it had to run usb_modeswitch first to put it into modem mode.
+
+With some of the modems listed in the [ModemManager Supported Devices list][modemmanager-supported-devices] you may find they struggle to connect, this is most likely due to [usb_modeswitch][usb_modeswitch-link] not knowing how to automatically switch the device to modem modem. In these cases you will need to have a look at your modem's data sheet and figure out how to force it to stay in modem mode.
```
Comment (craig-mulligan) [inline shared/networking/2.0.md]: `modem modem` ?

File: shared/insideResinOS/2.0.md [hunk 22]
```diff
@@ -0,0 +1,154 @@
...
+
+### Docker
+The docker engine is a lightweight container runtime that allows us to build and run linux containers on resinOS. ResinOS has been optimized to run docker containers and has been set up to use the journald log driver and DNSmasq for container DNS resolution.
+We use AUFS as the underlying storage driver since it is arguably the most production tested storage driver in the docker ecosystem. It also allows us to more easily support devices with older kernel versions and additionally gives us the ability to run on devices with Unmanaged NAND flash.
+
+### NetworkManager and ModemManager
+ResinOS uses NetworkManager accompanied by ModemManager, to deliver a stable and reliable connection to the internet, be it via ethenet, wifi or cellular modem. Additionally to make headless configuration of the device’s network easy, we have added a `system-connections` folder in the boot partition which is copied into `/etc/NetworkManager/system-connections`. So any valid NetworkManager connection file can just be dropped into the boot partition before device commissioning.
```
Comment (alisondavis17) [inline shared/insideResinOS/2.0.md]: should we clarify, where appropriate, that this is resinOS 2.0 that we are talking about? Since some people will still be running 1.x where this isn't true?

File: shared/networking/2.0.md (hunk 21 above)
Comment (craig-mulligan) [inline shared/networking/2.0.md]: probably needs to be `modem mode`

File: shared/insideResinOS/2.0.md (hunk 22 above)
Comment (alisondavis17) [inline shared/insideResinOS/2.0.md]: Saw the dropdown menu to select which docs to read about, may still be good to be explicit here in case somebody arrives on this page indirectly (e.g. via google search)

File: shared/networking/2.0.md [hunk 23]
```diff
@@ -0,0 +1,202 @@
...
+
+## Network Requirements
```
Comment (craig-mulligan) [inline shared/networking/2.0.md]: Aren't these the same as 1.x? Shouldn't it live in a partial?

File: shared/insideResinOS/2.0.md [hunk 24]
```diff
@@ -0,0 +1,154 @@
...
+ResinOS contains a partition named resin-conf that is meant to hold all this persistent data, inside we populate a Linux filesystem hierarchy standard with the rootfs paths that we require to be persistent. After this partition is populated we are ready to bind mount the respective rootfs paths to this read-write location, thus allowing different components (e.g. journald) to be able to write data to disk. A mechanism to purge this partition is provided, thus allowing users to rollback to an unconfigured ResinOS image.
+
+A diagram of our read-only rootfs can be seen below:
+
+<img src="/img/common/resinos/read-only-rootfs.png" width="90%">
+
+## Image Partition Layout
+
+The first partition, `resin-boot`, host boot important bits according to each board (e.g. kernel image, bootloader image). It also holds a very important file that you will find mentioned elsewhere in this document (i.e. `config.json`). The config.json file is the central point of configuring ResinOS and defining its behaviour, for example you can set your hostname, allow persistent logging, etc.
```
Comment (alisondavis17) [inline shared/insideResinOS/2.0.md]: seems like a typo in this sentence

File: shared/insideResinOS/2.0.md [hunk 25]
```diff
@@ -0,0 +1,154 @@
...
+`resin-rootB` is an empty partition that is only used when the rootfs is to be updated. We follow the A-B update strategy for the resin HostOS upgrades. Essentially we have one active partition that is the OS’s current rootfs and one dormant one that is empty, we download the new rootfs to the dormant partition and try to switch them, if the switch is successful the dormant partition becomes the new rootfs, if not, we go back to the old active partition.
+`resin-state` is the partition that holds persistent data as explained in the [Stateless and Read-only rootfs](#stateless-and-read-only-rootfs).
+`resin-data` is the partition that holds downloaded docker images. Generally any container data will be found here. If you want to read a bit more about the partition layout, have a look at the [resinOS github repo](https://github.com/resin-os/meta-resin/blob/master/meta-resin-common/classes/image_types_resin.bbclass#L20).
+
+## OS Yocto Composition
+
+The OS is composed of multiple yocto layers. The [Yocto Project](https://www.yoctoproject.org/) build system uses these layers to compile resinOS for the various [supported platforms](./supportedboards.md).
```
Comment (alisondavis17) [inline shared/insideResinOS/2.0.md]: capitalize Yocto throughout

File: shared/insideResinOS/2.0.md [hunk 26]
```diff
@@ -0,0 +1,154 @@
...
+|   Fido   |          1.8          |   Apr 2015   |      1.8.2      |   Community   |     13.0     |      1.26      |
+|   Dizzy  |          1.7          |   Oct 2014   |      1.7.3      |   Community   |     12.0     |      1.24      |
+|   Daisy  |          1.6          |   Apr 2014   |      1.6.3      |   Community   |     11.0     |      1.22      |
+|   Dora   |          1.5          |   Oct 2013   |      1.5.4      |   Community   |     10.0     |      1.20      |
+
+We will start looking into ResinOS’s composition from the core of the [Yocto Project](https://www.yoctoproject.org/), i.e. poky. Poky has released a whole bunch of versions and supporting all of them is not in the scope of our OS, but we do try to support its latest versions. This might sound ironic as we do not currently support poky’s last version (i.e. 2.1/Krogoth), but this is only because we did not need this version yet. We tend to support versions of poky based on what our supported boards require and also do a yearly update to the latest poky version for all the boards that can run that version. Currently we support three poky versions: 2.0/Jethro, 1.8/Fido and 1.6/Daisy.
```
Comment (alisondavis17) [inline shared/insideResinOS/2.0.md]: wouldn't use the word "ironic" here, maybe "unexpected" instead

File: shared/networking/1.X.md [hunk 27]
```diff
@@ -0,0 +1,159 @@
...
+* `123` UDP - For NTP time synchronisation.
+* `53` UDP - For DNS name resolution.
+
+Each of these should work with outward only (and inward once outward connection established) firewall settings.
+
+Additionally, if the network your device is connecting to works with whitelisting, you should whitelist the following domains on Port `80` and `443`:
+* `*.resin.io`
+* `*.pubnub.com`
+
+Additionally make an outgoing connection to `mixpanel.com`, but this is not a functional requirement for resin.io, but rather allows us to track some useful metrics.
```
Comment (alisondavis17) [inline shared/networking/1.X.md]: Have we always revealed our use of mixpanel?

File: shared/networking/1.X.md [hunk 28]
```diff
@@ -0,0 +1,159 @@
...
+
+### Multiple WiFi Connections
+
+Though we currently don't support multiple WiFi SSIDs through the user
+interface, this can be achieved by manually editing the `config.json` file on your SD card. To add a second wifi network to the configuration simply append the following to `"network/network.config":`:
+
+```JSON
+"files": {
+    "network/settings": "[global]\nOfflineMode=false\n\n[WiFi]\nEnable=true\nTethering=false\n\n[Wired]\nEnable=true\nTethering=false\n\n[Bluetooth]\nEnable=true\nTethering=false",
+    "network/network.config": "[service_home_ethernet]\nType = ethernet\nNameservers = 8.8.8.8,8.8.4.4\n\n[service_home_wifi]\nType = wifi\nName = My_Wifi_Ssid\nPassphrase = my super secret wifi passphrase\nNameservers = 8.8.8.8,8.8.4.4\n\n[service_office_wifi]\nType = wifi\nName = My_2nd_Wifi_Ssid\nPassphrase = my super sexy wifi\nNameservers = 8.8.8.8,8.8.4.4"
```
Comment (alisondavis17) [inline shared/networking/1.X.md]: can we not use "super sexy wifi" as the example...?

File: shared/networking/2.0.md [hunk 29]
```diff
@@ -0,0 +1,262 @@
...
+* [Setting a Static IP](#setting-a-static-ip)
+* [Cellular Modem Setup](#cellular-modem-setup)
+* [Changing the Network at Runtime](#changing-the-network-at-runtime)
+* [Network Requirements](#network-requirements)
+
+## Introduction
+
+In resinOS 2.0 the connectivity management has been change from [connman][connman-link] to [NetworkManager][networkmanager-link]. NetworkManager give the OS a bit more flexibility in the network setup and in conjunction with [ModemManager][modemmanager-link] allows resinOS to offer first class [GSM/Cellular support](#setup-a-cellular-connection).   
+
+All of the network configuration for resinOS can be done though files in the boot partition of your device. I you have a freshly downloaded resinOS `.img` you can mount it and inspect the `resin-boot` or `resin-flash` (for devices that boot from eMMC) partition. In the boot partition you will find a directory called `system-connections`.
```
Comment (alisondavis17) [inline shared/networking/2.0.md]: I should be If

File: shared/networking/2.0.md [hunk 30]
```diff
@@ -0,0 +1,262 @@
...
+* Huawei E3131 (USB Ethernet emulation)
+* [Fona 3G](https://learn.adafruit.com/adafruit-fona-3g-cellular-gps-breakout/overview) (USB AT command)
+* uBlox lisa-u200 (USB AT command)
+* Huawei ME909u-521 PCI-e 
+* Huawei E3533
+* Huawei E398-u1 (cdc-wdm0) --> This device took a while to connect, most likely because it had to run usb_modeswitch first to put it into modem mode.
+
+__Note:__ If your are powering your USB modem from a Raspberry Pi, it is a good idea to enable the full 1.2A current throughput for the USB ports, you can see how to do this [here](https://docs.resin.io/hardware/i2c-and-spi/#increase-usb-current-throughput-)
+
+With some of the modems listed in the [ModemManager Supported Devices list][modemmanager-supported-devices] you may find they struggle to connect, this is most likely due to [usb_modeswitch][usb_modeswitch-link] not knowing how to automatically switch the device to modem modem. In these cases you will need to have a look at your modem's data sheet and figure out how to force it to stay in modem mode.
```
Comment (alisondavis17) [inline shared/networking/2.0.md]: modem modem should be modem mode

File: shared/networking/2.0.md [hunk 31]
```diff
@@ -0,0 +1,262 @@
...
+
+## Changing the Network at Runtime
+
+Often there are times where the wifi network that the device will be provisioned into is not known before hand. In these cases the device needs a mechanism to be able to add its own wifi credentials during some kind of setup stage. For this reason we built the [resin wifi connect][resin-wifi-connect] project.
+
+Resin wifi connect enables the device to create a wireless access point called `ResinAP` (also customisable) which serves a captive portal. This allows your end user to connect to the device and add their wifi credentials. The device will then automatically leave the setup mode and connect to the specified user network.
+
+Under the hood resin wifi connect is interacting with NetworkManager via it's [DBUS][dbus-link] API. The DBUS API is a useful way to interact with the resinOS host NetworkManager and there are DBUS bindings for most languages. Below is minimal python example from the [NetworkManager examples](https://wiki.gnome.org/Projects/NetworkManager/Developers#Show_me_more_examples.21).
```
Comment (alisondavis17) [inline shared/networking/2.0.md]: it's should be its

File: shared/networking/2.0.md [hunk 32]
```diff
@@ -0,0 +1,262 @@
...
+settings = dbus.Interface(proxy, "org.freedesktop.NetworkManager.Settings")
+
+settings.AddConnection(con)
+```
+
+The above example will add a new wifi connection file to your hostOS NetworkManager configuration in `/etc/NetworkManager/system-connections`. It should be noted that you will not see a new file created in `resin-boot/system-connections` because there isn't a two way binding. The way it works is that on device boot, the files in `resin-boot/system-connections` is copied into `/mnt/state/root-overlay/etc/NetworkManager/system-connections` without removing any files from the destination. That directory is then bind mounted to `/etc/NetworkManager/system-connections` in the root filesystem on the Host.
+
+__Warning:__ It can be pretty dangerous if you install NetworkManager or python-networkmanager in your container, especially if you have `INITSYSTEM=on`, since systemd will automatically try to start your container NetworkManager and this will take your devices offline. It's very **important** to remember that making changes to the networking of a device is extremely **dangerous** and can lead to a device being unrecoverable, so excise caution with any of the above.
```
Comment (alisondavis17) [inline shared/networking/2.0.md]: excise should be exercise

File: shared/networking/2.0.md (hunk 10 above)
Comment (shaunmulligan) [inline shared/networking/2.0.md]: @craig-mulligan I don't really upder stand what you mean here.

File: config/dictionaries/os_version.json (hunk 2 above)
Comment (shaunmulligan) [inline config/dictionaries/os_version.json]: yeah, I mainly thought it would look weird in the URL, but you are probably right. I'll change it

File: shared/insideResinOS/2.0.md (hunk 16 above)
Comment (shaunmulligan) [inline shared/insideResinOS/2.0.md]: @alisondavis17 those links are referenced down the bottom of the doc, its just a markdown trick that allows you to use the same link in multiple places.

File: shared/networking/1.X.md (hunk 27 above)
Comment (shaunmulligan) [inline shared/networking/1.X.md]: yeah, people are pretty paranoid about their devices reaching out and connecting to random servers that they don't know about.

File: shared/networking/2.0.md (hunk 10 above)
Comment (craig-mulligan) [inline shared/networking/2.0.md]: Just asking what happens when 2.1 comes out? It won't find this file.
